openapi: '3.0.2'
info:
  title: 孔雀巢投票
  description: |
    # 简述
    给孔雀巢商家后台使用，线上服务器地址 <http://vote.kongquechao.com>

    # 验证授权
    这些API使用以下的授权验证方式
      - API Key  An API key is a token that a client provides when making API calls.
      
    <SecurityDefinitions />

  termsOfService: https://smartbear.com/terms-of-use/
  contact:
    name: Adam Smith
    url: https://github.com/metanoia1989
    email: m15171641694@163.com
  x-logo:
    url: './assets/images/logo-brand.png'
    altText: 孔雀巢投票
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: https://vote.kongquechao.com
    description: 线上服务器
  - url: http://cqc-vote.test
    description: 本地服务器

security:
  - BearerAuth: []
    
tags:
  - name: Auth
    description: 安全验证
  - name: Wechat
    description: 微信相关
  - name: Event
    description: 活动相关
    
paths:
  /api/wechat/login:
    get:
      tags:
        - Wechat
      summary: 微信静默登陆 
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                  description: 微信授权登陆code
              required:
                - code
      responses:
        '200':
          description: 静默登陆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'

  /api/wechat/share:
    post:
      tags:
        - Wechat
      summary: 获取微信分享参数
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: 分享的URL
              required:
                - code
      responses:
        '200':
          description: 微信分享参数
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShareParam'

  /api/even/{event_id}:
    get:
      tags:
        - Event
      summary: 获取活动详情
      security: 
        - BearerAuth: []
      parameters:
        - in: path
          name: event_id
          schema:
            type: integer
          required: true
          description: 活动ID
      responses:
        '200':
          description: 活动详情数据
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

  /api/competitors:
    get:
      tags:
        - Event
      summary: 活动作品或选手列表
      security: 
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                  description: 活动ID
                page:
                  type: integer
                  description: 第几页
                limit:
                  type: integer
                  description: 每页的个数
                title:
                  type: string
                  description: 作品或选手名称 
                subtitle:
                  type: string
                  description: 副标题
              required:
                - event_id
      responses:
        '200':
          description: 活动作品或选手列表数据
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersResponse'
    
components:
  securitySchemes:
    BearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer

  schemas:
    Response:
      description: 接口响应公共字段
      type: object
      properties:
        code:
          type: integer 
        msg:
          type: string
        data: {}
      required:
        - code
        - msg

    ObjectResponse:
      description: 任意对象数据的响应
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object
      

    LoginSuccess:
      description: 登陆成功的响应
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object 
              properties:
                token:
                  type: string
                open_id:
                  type: string

          example:
            code: 0
            msg: success
            data:
              token: VbmtO4RZKOPSyHl6L5i0d5kyqH6Q8MyK
              open_id: oniX0wJlqJyWHAx9B61im7Ow9WDA


    ShareParam:
      description: 微信分享参数
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object 
              properties:
                appId:
                  type: string
                nonceStr:
                  type: string
                timestamp:
                  type: integer
                url:
                  type: string
                signature:
                  type: string

          example:
            msg: success
            code: 0
            data:
              appId: APPID参数
              nonceStr: qweqwerqqer
              timestamp: 13423423
              url: http://sdfsdfsdf
              signature: 36234hsfgsdfsdf
    Event:
      description: 活动详情数据
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: object 
              properties:
                id:
                  type: integer
                add_time:
                  type: string
                start_time:
                  type: integer
                  description: 开始时间为0时，只要不超过结束时间，活动都在进行中
                end_time:
                  type: integer
                  description: 活动结束时间，为0表示永不结束
                is_del:
                  type: integer
                status:
                  type: integer
                  description: 0：正常 -1：暂停
                single_max_per_day:
                  type: integer
                  description: 每人每天最多可投票数
                need_login:
                  type: integer
                  description: 是否需要授权登陆 0：不需要，在微信端只要静默登陆 1：需要，在微信端要授权
                type:
                  type: string
                  description: 投票类型
                title:
                  type: string
                cover_url:
                  type: string
                subtitle:
                  type: string

          example:
            msg: success
            code: 0
            data:
              id: 1
              add_time: '2021-05-13 11:04:52'
              start_time: 0
              end_time: 0
              is_del: 0
              status: 0
              single_max_per_day: 5
              need_login: 0
              type: 未知类型投票
              title: 2021摄影大赛投票
              cover_url: http://vote.kongquechao.com/cam01.jpg
              subtitle: 2021省协摄影大赛投票

    Player:
      description: 选手详情数据
      type: object
      properties:
        id: 
          type: integer
          description: 选手ID
        type: 
          type: string
        cover_url:
          type: string
        subtitle:
          type: string
        event_id: 
          type: integer
          description: 活动ID
        serial_num: 
          type: integer
          description: 编号
        vote_num: 
          type: integer
          description: 票数
          
      example:
        id: 1
        type: 1
        title: 周录军
        cover_url:
        subtitle: 儿童摄影类
        event_id: 1
        serial_num: 1
        vote_num: 4682

    PlayersResponse:
      description: 选手列表
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Player'

      
